spring:
  application:
    name: iiot-backend

server:
  port: 8080

mqtt:
  broker-url: ${MQTT_BROKER_URL}
  client-id: iiot-backend
  topic: factory/line1/+

influx:
  url: http://influxdb:8086
  org: iiot
  bucket: sensors
  username: ${INFLUXDB_ADMIN_USER}
  password: ${INFLUXDB_ADMIN_PASSWORD}
